### ISSUE TITLE
Convert from WIF back to seed/mnemonic

### ISSUE THREAD

**Issue by msafi** [bitcoinjs/bip32#34]
The Bitcoin backend I use only stores the WIF. I would like to be able to show the user their mnemonic by calculating it from the WIF.

**Comment by lukechilds** [comment]
You can't calculate a mnemonic from a WIF.

They are different concepts. A mnemonic is used to derive a seed which is then used to seed multiple accounts, which can then derive multiple private keys.

Each private key can be represented by a WIF.

**Comment by junderw** [comment]
```
seed = hashes(mnemonic)
rootkey = morehashes(seed)
childkey = evenmorehashes(rootkey)
wif = wifencoding(childkey)
```

We can decode wif into a child key, but WIF throws away the chaincode, so we won't be able to derive any children. To do that you would need the xprv extended private key format, not WIF (toBase58() instead of toWIF()).

However, hash algorithms can not be reversed.

If you want the mnemonic, you need to store the mnemonic.

**Comment by msafi** [comment]
I'm a little confused. Bitcoin Core has the command `sethdseed` which accepts a WIF private key and it treats it as the seed for the HD wallet. It derives the other keys from it.

I do have the xprv, but anyway, if the algorithms being used are irreversible hashes then this is it :)

**Comment by junderw** [comment]
`sethdseed` accepts WIF??? lol

Well, then basically it's taking the private key data within the WIF and using it in place of the `seed` I mentioned in my simplified explanation instead of the hash of the mnemonic.
