### ISSUE TITLE
 Outdated secp256k1

### ISSUE THREAD

**Issue by dignifiedquire** [bitcoinjs/bip32#39]
The commit that tiny-secp256k1 pulls in on master is currently 3 years old, any reason not to update this to a more recent version? For example npmjs.com/package/secp256k1 has a much newer version and fallbacks for the brower as well

**Comment by electic** [comment]
Also running into issues where it doesn't compile with newer version of node due to a lot of v8 functions being deprecated.

**Comment by matt-scientist** [comment]
Seeing this deprecation warning stemming from tiny-secp256k1
```
DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**Comment by junderw** [comment]
> Seeing this deprecation warning stemming from tiny-secp256k1

1. That would be an issue for tiny-secp256k1
2. tiny-secp256k1 has been using Buffer.alloc and Buffer.from since the first release, so I think something is wrong with your lock file (maybe you have one of tiny-secp256k1's old dependency locked to an old version)

Here's the main js file from the first commit back in 2018. No usage of `Buffer()` directly.

https://github.com/bitcoinjs/tiny-secp256k1/blob/c5ef90a465d88dde619d2b53d8a33162daa70425/ecurve.js

**Comment by weskerfoot** [comment]
Can we get this fixed? It's causing issues with transitive dependencies when trying to e.g. use newer versions of Electron.

**Comment by junderw** [comment]
New version of tiny-secp256k1 will use WASM compiled from the latest version of libsecp256k1.

bip32 will be updated to support schnorr signatures soon using WASM. Also, tiny-secp256k1 interface will be injectable, so you can provide your own implementation if you require something besides WASM.

**Comment by weskerfoot** [comment]
> New version of tiny-secp256k1 will use WASM compiled from the latest version of libsecp256k1.
> 
> bip32 will be updated to support schnorr signatures soon using WASM. Also, tiny-secp256k1 interface will be injectable, so you can provide your own implementation if you require something besides WASM.

That sounds like a great solution to solve everyone's varying needs! +1
