### ISSUE TITLE
Path to derive grandchildren from children

### ISSUE THREAD

**Issue by eozturk1** [bitcoinjs/bip32#43]
I am trying to derive grandchildren of a master key and this can be done by using the path `m/0/0` -- which requires the master key. To derive the grandchildren from children, I have tried the following:

    var node = bip32js.bip32.fromBase58('<some_private_key>')
    var child = node.derivePath('m/0')
    alert("Child: " + JSON.stringify(child));
    var grandChild = child.derivePath('m/0'); // +1 depth from the child (i.e., grandchild)
    alert("Grandchild: " + JSON.stringify(grandChild));

But this gives an `Expected master, got child` error. I also tried `child.derivePath('0/0')` which uses the same notation of `m/0` by adding 1 more depth to the key in use but the final depth is 3 instead of 2.

Is the correct path for deriving grandchildren from children `0` in this case (i.e., `child.derivePath('0')`)?

(I am not sure whether opening an issue is the correct thing to do for these questions. I looked for a channel to ask but couldn't find one. Stackoverflow did not seem too interested in these questions since it is specific to a library. If there is a better way to ask these, I'd appreciate it if you could share.)

**Comment by junderw** [comment]
If you're only deriving one layer,
use `derive` (for `0` would be `derive(0)`)
or `deriveHardened` (for `0'` would be `deriveHardened(0)`)
instead of `derivePath`

`derivePath` is just a shortcut for people needing to do multiple layers without needing to write a loop etc.

`derivePath('0')` would also work, but it will internally just call `derive(0)`
