### ISSUE TITLE
Derivation path elements > 2147483647 should throw?

### ISSUE THREAD

**Issue by landabaso** [bitcoinjs/bip32#70]
As this module is implemented now, It is possible to derive paths such as this one:

`xprv9s21ZrQH143K31xYSDQpPDxsXRTUcvj2iNHm5NUtrGiGG5e2DtALGdso3pGz6ssrdK4PFmM8NSpSBHNqPqm55Qn3LqFtT2emdEXVYsCzC2U/2147483648`

or 

`xpub661MyMwAqRbcFW31YEwpkMuc5THy2PSt5bDMsktWQcFF8syAmRUapSCGu8ED9W6oDMSgv6Zz8idoc4a6mr8BDzTJY47LJhkJ8UB7WEGuduB/2147483648`

(note the unhardened 2147483648)

This module will handle 2147483648 as if it was a derivation to `0'` (zero hardened).

I understand the reasoning behind this. The problem is Bitcoin Core assumes these paths are wrong.

See for example this fixture here which is expected to fail:

https://github.com/bitcoin/bitcoin/blob/fcff639af137f2a6636ef454d0404b969ab7772e/src/test/descriptor_tests.cpp#L418

I was considering a PR to fix `derivePath` (the function that accepts a string path). But the thing is a PR to fix this "issue" may break other projects that rely on this behaviour...
I'll wait to see what you guys thing about it.

**Comment by junderw** [comment]
I am not sure what to think about this.

I am open to changing it in the next major release, whenever that would be, but this is a breaking change.

It might be better to manage this at the output descriptor level, since the BIP32 standard defines the index as a 32 bit unsigned integer, and the whole "0x80000000 is just a ' and means 'hardened'" is a human readability thing.

Since output descriptors are human readable, it makes sense to have the error be at the parsing logic since it would be ambiguous to have two representations of the same index.

**Comment by junderw** [comment]
Also, keep in mind that the BIP32 spec makes no clear rules about the `h/H/'` hardening notation. It's all just 32 bit unsigned integers.

**Comment by landabaso** [comment]
That's what I was afraid of. This "fix" might break other people's stuff.
I'm dealing with it at the descriptor level. Thanks!
