### ISSUE TITLE
Understanding the BIP32 version

### ISSUE THREAD

**Issue by matiasim** [bitcoinjs/bip32#72]
I'm getting an error when running this library on testnet. Specifically I'm getting the TypeError `TypeError('Invalid network version')`. I'm trying to understand this better but I'm having trouble wrapping my head around it. 

From the BIP32 wiki, the version is supposed to be the first 4 bytes of a pub/priv key. e.g.
`testnet: 0x043587CF public, 0x04358394 private` 

However, in this bip32 repo, the Type error throws on ([here](https://github.com/bitcoinjs/bip32/blob/98a057b6af1ec52c538797811c0fe685e09e1f30/src/bip32.js#L281)) :
```
const version = buffer.readUInt32BE(0)
if (version !== network.bip32.private && version !== network.bip32.public)
            throw new TypeError('Invalid network version');
```

I'm struggling to understand how can this statement ever be true? Given:
network.bip32.private =  0x04358394 //testnet
network.bip32.public =  0x043587CF //testnet

then isn't it basically asking if `version` is equal to both public and private versions?

Furthermore, a few lines later, the statement ([here](https://github.com/bitcoinjs/bip32/blob/98a057b6af1ec52c538797811c0fe685e09e1f30/src/bip32.js#L301)):
```if (version === network.bip32.private) { ... ```

Given the previous equality condition, wouldn't this line always be true?

**Comment by junderw** [comment]
`version !== network.bip32.private` = "If version is not the private version."
`&&` = "and"
`version !== network.bip32.public` = "If version is not the public version."

In order words: "If version is not the public nor private version." which is correct.

The if statement later on is saying "If version IS the private version."

Are you trying to decode a Ypub or Zpub instead of an xpub? The default versions only support extended keys that start with xpub (public) and xprv (private)

**Comment by matiasim** [comment]
of course! thanks!

**Comment by LeeKorbisCa** [comment]
@junderw I didn't want to open a new issue for this since there are many already on the subject.

It seems there's a nice way to pass in the correct version bytes. It could be really nice if bip32 included this function (maybe renamed to something better), since it's bip32 that consumes the output (rather than include it in bitcoinjs-lib). Let me know if you'd like me to open a PR. It does rely on bitcoinjs-lib's Network type, so, I think it could be best to place this code into a "contrib" directory, in order to avoid adding a dependency. It was really a pain getting to this point so I'm sure others would appreciate it... 

```js
// Thank you https://github.com/bitcoinjs/bitcoinjs-lib/issues/1238#issuecomment-426880691
const fixNetworkVersionBytes = (xkey: string, network: bitcoin.Network) => {
  let type = undefined;
  if (xkey.slice(1, 4) == "prv") type = "private";
  if (xkey.slice(1, 4) == "pub") type = "public";
  if (type === undefined) throw new Error("Bad xkey prefix");

  let data = b58.decode(xkey);
  data = data.slice(4);
  data = Buffer.concat([Buffer.from(network.bip32[type].toString(16).padStart(8, '0'),'hex'), data]);
  return b58.encode(data);
};
```
